config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  resources :hunters
  resources :mining_types
  resources :posts
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hunter.rb
class Hunter < ApplicationRecord
    has_and_belongs_to_many :posts
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :mining_type, optional: true
    has_and_belongs_to_many :hunters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        end
        
        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/hunters_controller.rb
class HuntersController < ApplicationController
  before_action :set_hunter, only: %i[ show edit update destroy ]

  # GET /hunters or /hunters.json
  def index
    @hunters = Hunter.all
  end

  # GET /hunters/1 or /hunters/1.json
  def show
  end

  # GET /hunters/new
  def new
    @hunter = Hunter.new
  end

  # GET /hunters/1/edit
  def edit
  end

  # POST /hunters or /hunters.json
  def create
    @hunter = Hunter.new(hunter_params)

    respond_to do |format|
      if @hunter.save
        format.html { redirect_to hunter_url(@hunter), notice: "Hunter was successfully created." }
        format.json { render :show, status: :created, location: @hunter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hunter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hunters/1 or /hunters/1.json
  def update
    respond_to do |format|
      if @hunter.update(hunter_params)
        format.html { redirect_to hunter_url(@hunter), notice: "Hunter was successfully updated." }
        format.json { render :show, status: :ok, location: @hunter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hunter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hunters/1 or /hunters/1.json
  def destroy
    @hunter.destroy

    respond_to do |format|
      format.html { redirect_to hunters_url, notice: "Hunter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hunter
      @hunter = Hunter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hunter_params
      params.require(:hunter).permit(:name, :image, :gun)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:name, :title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [:new, :edit, :update, :create]
  before_action :set_hunters, only: [:new, :edit, :update, :create]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end  
  
  private

  def set_mining_type_options
    @mining_type_options = MiningType.all.pluck(:name, :id)
  end

  def set_hunters
    @hunters = Hunter.all
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:name, :title, :mining_type_id, hunter_ids: [])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        cookies[:curso] = "Teste cookies etc etc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def locale
        I18n.locale == :en ? "United States": "Brazilian Portuguese"
    end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/hunters_helper.rb
module HuntersHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/pc_types_helper.rb
module PcTypesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homepage/index.html.erb
<h1>Homepage#index</h1>
<p>Find me in app/views/homepage/index.html.erb</p>

app/views/hunters/_form.html.erb
<%= form_with(model: hunter, local: true) do |form| %>
  <% if hunter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hunter.errors.count, "error") %> prohibited this hunter from being saved:</h2>

      <ul>
      <% hunter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :gun %>
    <%= form.text_field :gun %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hunters/edit.html.erb
<h1>Editing Hunter</h1>

<%= render 'form', hunter: @hunter %>

<%= link_to 'Show', @hunter %> |
<%= link_to 'Back', hunters_path %>

app/views/hunters/hunter_info/_index_description.html.erb
<td><%= hunter.name %></td>
<td><%= image_tag(hunter.image || "https://www.ofertadia.com.br/wp-content/themes/deals/images/store-default.png", width:100, height: 100) %></td>
<td><%= image_tag(hunter.gun || "https://www.ofertadia.com.br/wp-content/themes/deals/images/store-default.png", width:100, height: 100) %></td>

app/views/hunters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hunters</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Gun</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hunters.each do |hunter| %>
      <tr>
        <%= render "hunters/hunter_info/index_description", hunter: hunter if hunter %>
        <td><%= link_to 'Show', hunter %></td>
        <td><%= link_to 'Edit', edit_hunter_path(hunter) %></td>
        <td><%= link_to 'Destroy', hunter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Hunter", new_hunter_path, class:"btn btn-primary btn-lg" , role:"button" %>
<%= link_to "Menu", root_path, class:"btn btn-primary btn-lg" , role:"button" %>

app/views/hunters/new.html.erb
<h1>New Hunter</h1>

<%= render 'form', hunter: @hunter %>

<%= link_to 'Back', hunters_path %>

app/views/hunters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hunter.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @hunter.image %>
</p>

<p>
  <strong>Gun:</strong>
  <%= @hunter.gun %>
</p>

<%= link_to 'Edit', edit_hunter_path(@hunter) %> |
<%= link_to 'Back', hunters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-5-theme/1.3.0/select2-bootstrap-5-theme.min.css" integrity="sha512-z/90a5SWiu4MWVelb5+ny7sAayYUfMmdXKEAbpj27PfdkamNdyI3hcjxPxkOPbrXoKIm7r9V2mElt5f1OtVhqA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <ul class="nav justify-content-end">
      <li class="nav-item">
       <p> <%= link_to t('language.portuguese'), root_path(locale: 'pt-BR'), class: "nav-link" %> </p>
      </li>
      <li class="nav-item">
      <p><%= link_to t('language.english'), root_path(locale: 'en'), class: "nav-link" %></p>
      </li>
    </ul>
      <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.full.min.js"></script>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1>Editing Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Show', @mining_type %> |
<%= link_to 'Back', mining_types_path %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mining Types</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.name %></td>
        <td><%= mining_type.title %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: t('links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_mining_type_path do %>
<%= button_tag "New Mining Type", class:"btn btn-primary col-md-1" %>
<% end %>
<%= link_to root_path do %>
<%= button_tag "Menu", class:"btn btn-primary col-md-1" %>
<% end %>

app/views/mining_types/new.html.erb
<h1>New Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Back', mining_types_path %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mining_type.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @mining_type.title %>
</p>

<%= link_to 'Edit', edit_mining_type_path(@mining_type) %> |
<%= link_to 'Back', mining_types_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :mining_type_id %>
    <%= form.select("mining_type_id", @mining_type_options, { include_blank: "Selecione uma opção" }) %>
  </div>
  <div class="field col-md-3">
    <%= form.label :hunter_ids %>
    <%= form.select("hunter_ids",
      options_from_collection_for_select(@hunters, :id, :name),
      { include_blank: "Selecione uma opção" },
      { class: "form-select form-select-sm", multiple: true }
    ) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/hunter_details/_index_description.html.erb
<td><%= image_tag(post.hunter.avatar_url || "https://www.ofertadia.com.br/wp-content/themes/deals/images/store-default.png", width:100, height: 100) %></td>
<td><%= image_tag(post.hunter.gun_url || "https://www.ofertadia.com.br/wp-content/themes/deals/images/store-default.png", width:100, height: 100) %></td>
<%= render "posts/hunter_details/index_description", post: post if post.hunter %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class='table'>
  <thead>
    <tr>
      <th><%= @posts.human_attribute_name(:name)%></th>
      <th><%= @posts.human_attribute_name(:title)%></th>
      <th>Hunter Name </th>
      <th>Hunter Image </th>
      <th>Gun</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td>
          <%=  (post.hunters.map(&:name).to_sentence) %>
        </td>
        <td>
          <%= image_tag (post.hunters.map(&:image).to_sentence), width:100, height: 100 %>
        </td>
        <td>
          <%= image_tag (post.hunters.map(&:gun).to_sentence), width:100, height: 100 %>
        </td>
        <td><%= link_to t('links.show'), post %></td>
        <td><%= link_to t('links.edit'), edit_post_path(post) %></td>
        <td><%= link_to t('links.delete'), post, method: :delete, data: { confirm: t('links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Post", new_post_path, class:"btn btn-primary btn-lg" , role:"button" %>
<%= link_to "Menu", root_path, class:"btn btn-primary btn-lg" , role:"button" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/_menu.html.erb
<div>
    <%= link_to "Posts", posts_path, class:"btn btn-primary btn-lg" , role:"button" %>
    <%= link_to "Mining types", mining_types_path, class:"btn btn-primary btn-lg" , role:"button" %>
    <%= link_to "Hunters", hunters_path, class:"btn btn-primary btn-lg" , role:"button" %>
</div>
<br>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"> <%=t('welcome')%> </h1>
  <p class="lead"><%=t('message.description')%></p>
  <hr class="my-4">
  <p><%=t('message.options')%></p>
  <%= render "menu" %>
</div>
